version: '3.2'

services:
    api:
        image: ghcr.io/codize-dev/piston@sha256:c8a33a56fe24fa23145f14de3013a96656cbd105d7b0e19655f526ec03d6151e
        container_name: piston_api
        restart: always
        privileged: true
        ports:
            - 2000:2000
        volumes:
            - ./data/piston/packages:/piston/packages
        tmpfs:
            - /tmp:exec
