version: '3.2'

services:
    api:
        image: ghcr.io/codize-dev/piston@sha256:bb9ae8af898f59dbb0cf675e761b485ae643e2968ea1642dc559002c9436e2f3
        container_name: piston_api
        restart: always
        privileged: true
        ports:
            - 2000:2000
        volumes:
            - ./data/piston/packages:/piston/packages
        tmpfs:
            - /tmp:exec
