version: '3.2'

services:
    api:
        image: ghcr.io/codize-dev/piston@sha256:daf8db49d7a8706a6dc4485aff3a2db3aacf4b3990813b58c2fa3d86a9a3644b
        container_name: piston_api
        restart: always
        privileged: true
        ports:
            - 2000:2000
        volumes:
            - ./data/piston/packages:/piston/packages
        tmpfs:
            - /tmp:exec
